// Markdown export helpers. The report body is already markdown, so export is
// mostly about adding a provenance footer and a safe filename.

export function toMarkdownDocument(
  contentMarkdown: string,
  meta: { generatedAt?: Date } = {},
): string {
  const stamp = (meta.generatedAt ?? new Date()).toISOString();
  const footer = `\n\n---\n\n_Generated by MissionBrief on ${stamp}. Every figure is traceable to the cited source files._\n`;
  return contentMarkdown.trimEnd() + footer;
}

export function toSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}
